services:
  # 后端服务
  - type: web
    name: chatgpt-fake-backend
    runtime: node
    region: singapore
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # 前端服务
  - type: web
    name: chatgpt-fake-frontend
    runtime: static
    buildCommand: cd front && npm install && npm run build
    staticPublishPath: front/dist
    envVars:
      - key: VITE_API_URL
        value: https://chatgpt-fake-backend.onrender.com
